echo "BUILD ENVIRONMENT STATUS"
echo "Component                        Expected                     Actuals"
echo "---------                        --------                     -------"
echo " |- doxygen version              1.8.17                       $(doxygen --version)"
echo " |- make version                 GNU Make 4.2.1               $(make --version | head -1)"
echo " |- cmake version                3.16.3                       $(cmake --version | head -1)"
echo " |- autoconf version             2.69                         $(autoconf --version | head -1)"
echo " |- glibcxx highest version      <=GLIBCXX_3.4.28             $(strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX | tail -2 | head -1)"
echo " |- c++ --version                10.0.0                       $(c++ --version | head -1)"
echo " |- cc --version                 10.0.0                       $(cc --version | head -1)"
echo " |- ldd --version                2.31                         $(ldd --version | head -1)"
