FIND_PATH(LIBUV_INCLUDE_DIR NAMES uv.h)

FIND_LIBRARY(LIBUV_LIBRARY NAMES libuv.so)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	LIBUV
	REQUIRED_VARS
	LIBUV_LIBRARY
	LIBUV_INCLUDE_DIR
)

if(NOT TARGET LibUV::uv)
	add_library(LibUV::uv SHARED IMPORTED)
	set_target_properties(LibUV::uv PROPERTIES
		IMPORTED_LOCATION ${LIBUV_LIBRARY}
		INTERFACE_INCLUDE_DIRECTORIES "${LibUV_INCLUDE_DIR}"
	)
endif()
