FIND_PATH(LIBUV_INCLUDE_DIR NAMES uv.h)

FIND_LIBRARY(LIBUV_LIBRARY NAMES libuv.a)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	LIBUV
	REQUIRED_VARS
	LIBUV_LIBRARY
	LIBUV_INCLUDE_DIR
)

if(NOT TARGET LibUV::uv)
	add_library(LibUV::uv STATIC IMPORTED)

	find_package(Threads)
	set_target_properties(LibUV::uv PROPERTIES
		IMPORTED_LOCATION ${LIBUV_LIBRARY}
		INTERFACE_LINK_LIBRARIES Threads::Threads
		INTERFACE_INCLUDE_DIRECTORIES "${LibUV_INCLUDE_DIR}"
	)
endif()
