FIND_PATH(LIBUV_INCLUDE_DIR NAMES uv.h)

FIND_LIBRARY(LIBUV_LIBRARY NAMES libuv.a)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	LIBUV
	REQUIRED_VARS
	LIBUV_LIBRARY
	LIBUV_INCLUDE_DIR
)

add_library(LibUV::uv STATIC IMPORTED)
set_target_properties(LibUV::uv PROPERTIES
	IMPORTED_LOCATION ${LIBUV_LIBRARY}
	INTERFACE_INCLUDE_DIRECTORIES "${LibUV_INCLUDE_DIR}"
)
